window.IngredientsView = {
    template: `
        <div style="position: sticky; top: 0; z-index: 100; background-color: var(--md-sys-color-background);">
            <header class="dialog-header" style="padding: 16px 24px 8px; display: flex; align-items: center; border-bottom: none;">
                <button type="button" id="close-ingredients-view" style="background: transparent; border: 1px solid var(--md-sys-color-outline); border-radius: 50%; width: 40px; height: 40px; display: flex; align-items: center; justify-content: center; cursor: pointer; color: var(--md-sys-color-on-surface); padding: 0;">
                    <span class="material-icons">arrow_back</span>
                </button>
                <h2 style="flex: 1; margin: 0 0 0 16px; font-family: var(--font-family-serif); font-size: 24px; color: var(--md-sys-color-on-surface);">Ingredientes</h2>
            </header>

            <div class="search-bar-container" style="padding: 0 24px 16px;">
                <div class="search-bar" style="background-color: var(--md-sys-color-surface-variant); border-radius: 28px; padding: 0 16px; height: 56px; display: flex; align-items: center; width: 100%;">
                    <span class="material-icons search-icon" style="color: var(--md-sys-color-on-surface-variant); margin-right: 12px; display: flex; align-items: center;">search</span>
                    <input type="text" id="ingredients-search" placeholder="Buscar ingrediente..." style="border: none; background: transparent; height: 100%; flex: 1; font-size: 16px; color: var(--md-sys-color-on-surface); outline: none; padding: 0;">
                </div>
            </div>
        </div>

        <div id="ingredients-manager-list" style="padding: 8px 24px 100px;">
            <!-- Dynamic List -->
        </div>

        <!-- Section Selector Dialog -->
        <dialog id="section-selector-dialog" class="bottom-sheet-dialog">
            <div class="dialog-content">
                <header class="dialog-header" style="display: flex; align-items: center; justify-content: space-between;">
                    <div style="width: 40px;"></div> <!-- Spacer for balance -->
                    <h3 style="flex: 1; text-align: center; margin: 0; font-family: var(--font-family-serif);">Asignar Sección</h3>
                    <button type="button" class="icon-btn" id="close-section-selector" style="border: 1px solid var(--md-sys-color-outline); background: transparent; border-radius: 50%; width: 40px; height: 40px; display: flex; align-items: center; justify-content: center; color: var(--md-sys-color-on-surface);">
                        <span class="material-icons">close</span>
                    </button>
                </header>
                <div id="section-options-list" style="padding: 0 16px 24px;">
                    <!-- Options generated by JS -->
                </div>
            </div>
        </dialog>
    `
};
